<a href="https://colab.research.google.com/github/mahamoorthi22007/AI-Internship/blob/main/Bi_Directional_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/fake_news_dataset.csv')

In [ ]:
df.head()

,id,title,author,text,state,date_published,source,category,sentiment_score,word_count,...,num_shares,num_comments,political_bias,fact_check_rating,is_satirical,trust_score,source_reputation,clickbait_score,plagiarism_score,label
0,1,Breaking News 1,Jane Smith,This is the content of article 1. It contains ...,Tennessee,30-11-2021,The Onion,Entertainment,-0.22,1302,...,47305,450,Center,FALSE,1,76,6,0.84,53.35,Fake
1,2,Breaking News 2,Emily Davis,This is the content of article 2. It contains ...,Wisconsin,02-09-2021,The Guardian,Technology,0.92,322,...,39804,530,Left,Mixed,1,1,5,0.85,28.28,Fake
2,3,Breaking News 3,John Doe,This is the content of article 3. It contains ...,Missouri,13-04-2021,New York Times,Sports,0.25,228,...,45860,763,Center,Mixed,0,57,1,0.72,0.38,Fake
3,4,Breaking News 4,Alex Johnson,This is the content of article 4. It contains ...,North Carolina,08-03-2020,CNN,Sports,0.94,155,...,34222,945,Center,TRUE,1,18,10,0.92,32.20,Fake
4,5,Breaking News 5,Emily Davis,This is the content of article 5. It contains ...,California,23-03-2022,Daily Mail,Technology,-0.01,962,...,35934,433,Right,Mixed,0,95,6,0.66,77.70,Real

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
l=LabelEncoder()

In [ ]:
df['label']=l.fit_transform(df['label'])

In [ ]:
x=df['text']
y=df['label']

In [ ]:
y.value_counts()

label
0    2026
1    1974
Name: count, dtype: int64

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
from tensorflow.keras.layers import LSTM,Dense,Bidirectional,Embedding

In [ ]:
voc_size=5000

In [ ]:
msg=x.copy()

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()#for stemming purpose -normalize the words(run,ran,running)

In [ ]:
corpus=[]
for i in range(len(msg)):
  review=re.sub('[^a-zA-Z]',' ',msg[i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',
 'content articl contain detail analysi report',

In [ ]:
onehot=[one_hot(words,voc_size) for words in corpus]
print(onehot)

[[2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 234, 3687, 811], [2002, 4746, 2405, 

In [ ]:
#Embedding
sen_len=20
embedding=pad_sequences(onehot,padding='pre',maxlen=sen_len)
print(embedding)

[[   0    0    0 ...  234 3687  811]
 [   0    0    0 ...  234 3687  811]
 [   0    0    0 ...  234 3687  811]
 ...
 [   0    0    0 ...  234 3687  811]
 [   0    0    0 ...  234 3687  811]
 [   0    0    0 ...  234 3687  811]]

In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sen_len))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
import numpy as np
in_x=np.array(embedding)
in_y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(in_x,in_y,test_size=0.33,random_state=42)

In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=32)

Epoch 1/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 8s 46ms/step - accuracy: 0.4948 - loss: 0.6943 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 2/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - accuracy: 0.4978 - loss: 0.6934 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 3/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - accuracy: 0.4955 - loss: 0.6935 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 4/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - accuracy: 0.5052 - loss: 0.6932 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 5/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.4933 - loss: 0.6935 - val_accuracy: 0.5091 - val_loss: 0.6931
Epoch 6/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5052 - loss: 0.6934 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 7/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.5052 - loss: 0.6932 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 8/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 7s 51ms/step - accuracy: 0.5052 - loss: 0.6933 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 9/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - accuracy: 0.5052 - loss: 0.6932 - val_accuracy: 0.5091 - val_loss: 0.6930
Epoch 10/10
84/84 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - accuracy: 0.5052 - loss: 0.6933 - val_accuracy: 0.5091 - val_loss: 0.6931